name: Run Cypress Test SuiteA

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.16.0

    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests and send results
      run: |
        npm run testsuite:a
        
        if [$? -eq 0]; then
            TEST_RESULT="All specs passed!"
        else
            TEST_RESULT="Some tests failed"
        fi
        
        curl -X POST \
        -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        "https://api.github.com/repos/pabloZenledger/frontend-cicd/actions/workflows/e2eResultHandler.yml/dispatches" \
        -d '{"event_type":"test_result","client_payload":{"result": "'"$TEST_RESULT"'"}}'
